project:
  type: website
  output-dir: docs

website:
  title: "Matt's Baby Stats"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mtqoi/baby_stats
      - icon: twitter
        href: https://twitter.com/mtqoi
      - icon: linkedin
        href: https://www.linkedin.com/in/mattcthornton/
format:
  html:
    theme: yeti
    css: styles.css
    code-overflow: wrap

execute:
  freeze: auto

