project:
  type: website
  output-dir: docs

website:
  title: "Matt's Baby Stats"
  twitter-card: true
  google-analytics: 
    tracking-id: "G-FB820BRRJK"
    anonymize-ip: true
  cookie-consent: 
    type: express
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/mtqoi/baby_stats
      - icon: twitter
        href: https://twitter.com/mtqoi
      - icon: linkedin
        href: https://www.linkedin.com/in/mattcthornton/
  
format:
  html:
    theme: yeti
    css: styles.css
    code-overflow: wrap
    title-block-banner: false

execute:
  freeze: auto
  
  




